* Certificaat
** Definition
Certificaat is an general-purpose ACME client, fully compatible with the Let’s Encrypt CA.

*** Challenges

Certificaat will honor all challenges defined in the ACME specification, but please note that Let’s Encrypt CA does not support the OOB challenge and that TLS-SNI comes in two flavors. 

| Challenge                             | Option identifier       | Let’s Encrypt | Certificaat |
| HTTP                                  | http-01                 | ✓             | ✓           |
| DNS                                   | dns-01                  | ✓             | ✓           |
| TLS with Server Name Indication (SNI) | tls-sni-01 & tls-sni-02 | ✓ & ✕         | ✓           |
| Out-of-Band                           | oob-01                  | ✕             | ✓           |


** Usage
*** Command line

Certificaat releases come as a self-contained binary requiring
Java. Drop it in your ~PATH~ and run it on the command line.  

Type ~certificaat -h~ to familiarize yourself with the input it
expects.

By default, Certificaat will use the staging server that creates dummy
certificates. This is so you can practice until you are ready to issue
a production certificate.

| Staging                                            | Production             |
| https://acme-staging.api.letsencrypt.org/directory | acme://letsencrypt.org |

To get a certificate for a domain, you need to run ~certificaat~ twice with different options:

1. ~certificaat authorize~
2. ~certificaat request~

Forever thereafter, the certificate can be renewed in one pass with ~certificaat renew~. 

**** Authorization

#+BEGIN_SRC shell
certificaat authorize -m example.com -n www.example.com -a joe@example.com -c http-01
#+END_SRC

During this phase, certificaat will, if needed, register a user
account with the ACME CA, and gather the information about the domain
you want to authorize.

- The “-m” option indicates the domain you want to authorize. It will feature in the Subject name of the final X.509 certificate.
- The “-a” option is the email address used by the CA to send expiry reminders.
- The “-n” option is an additional domain name you want to authorize. It will feature in the Subject Alternative Name (SAN) of the certificate. Repeat this option for all required names. Caution: there is a hard limit imposed by the CA. 
- The “-c” option is the challenge you want to complete. Repeat this option if you want to offer the CA multiple challenges. 
- The “-u” option is the URI to the ACME CA. 

Before exiting, ~certificaat~ will display instructions pertaining to the challenge. This is the time to satisfy the requirements (for example, configuring DNS records or preparing your web server). You are now ready for the second phase. 

**** Request

#+BEGIN_SRC shell
certificaat request -m example.com -n www.example.com -o "Example corp." 
#+END_SRC

During this phase, the challenges will be triggered and, if successfully completed, a certificate downloaded and saved to disk.

**** Info

#+BEGIN_SRC shell
certificaat info -m example.com
#+END_SRC

Certificaat will display a summary of the certificate. 

**** Renew

#+BEGIN_SRC shell
certificaat renew -m example.com 
#+END_SRC

This command can be integrated in an automated workflow. For example, as a cron job.

#+BEGIN_SRC shell
5 8 1 * * certificaat renew -m example.com && /usr/sbin/service nginx reload
#+END_SRC
*** Boot

 
